[[language]]
name = "python"
auto-format = true

[language.formatter]
command = "black"
args = ["-l", "79", "-q", "-"] 

[[language]]
name = "c"
auto-format = true

[language.formatter]
command = "clang-format"
args = ["--style", "gnu"] 

[[language]]
name = "java"
auto-format = true

[language.formatter]
command = "clang-format"
args = ["--style", "gnu"] 

[[language]]
name = "sql"
language-servers = ["sqruff"]

[language.formatter]
command = "sqruff"
args = ["fix"] 

[language-server.sqruff]
command = "sqruff"
args = ["lsp"]
